package com.nsoft.github.data.local.room

public const val DATABASE_VERSION = 1
public const val DATABASE_NAME = "database_file"
public const val REPOSITORIES_TABLE_NAME = "repositories_table"
public const val FAVORITES_TABLE_NAME = "favorite_table"
// And the things for the primary keys
/**
 * This "id" isn't the real primary key of the "repositories" table, the real primary key is autogenerated
 * and is essentially same as to what "rowId" would have been if items were just being poured in if
 * implicit sorting wouldn't be happening at insertion time.
 *
 * This is why we can't use it as a primary key, because when repositories with smaller "id"s arrive
 * from the API, they will push items that were e.g. our first 3 items down and take their places.
 *
 * We want to retain the ordering that they came in from the API itself
 */
public const val REPOSITORIES_PRIMARY_KEY = "id"

/**
 * The primary key of the favorites table - "repoId"
 */
public const val FAVORITES_PRIMARY_KEY = "repoId"

public const val COLLABORATORS_TABLE_NAME = "collaborators_table"
